language: node_js
node_js:
  - 16.3.0
jobs:
  include:
    - stage: "Linting"
      name: "ES Lint Checks"
      script: yarn lint
    - stage: "Tests"
      name: "Unit Tests and Code Coverage Report"
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
    

